### 회원가입 
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
   "email": "example4@example.com",
   "password": "eXampLeP@ss",
   "passwordconfirm": "eXampLeP@ss",
   "name": "관리자"
}