@host = http://localhost:3000/api/products

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwMDgzNDgyNiwiZXhwIjoxNzAwODc4MDI2fQ.XyZygaee_9L113Sw4ymDyfTc-RcJyg9jM_TRHg360VM

### 상품 생성
POST {{host}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
   "title": "킨더조이",
   "description": "장난감이 들어있는 초콜렛"
}

