@host = http://localhost:3000/api/users

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTcwMDcyMTIxMCwiZXhwIjoxNzAwNzY0NDEwfQ.sezAhPnk8Skgqh6Dz0lYLFtHSsRsNbL-Jm-cdStqJjk
### 내 정보 조회
GET {{host}}/me
Authorization: Bearer {{accessToken}}